//! Errors produced by ruff. Generated by error-chain.

use nom::Needed;
use nom::Err;

error_chain! {
    foreign_links {
        NomError(Err) #[doc="A wrapper for a Nom error."];
        IoError(::std::io::Error) #[doc="A wrapper for std's IO error."];
    }

    errors {
        /// Produced when a parser doesn't get enough data to finish parsing.
        NotEnoughDataError(needed: Needed) {
            description("Not enough data to parse!")
            display("Need {} more bytes to successfully parse!", match *needed {
                Needed::Unknown => "Unknown".to_string(),
                Needed::Size(size) => size.to_string()
            })
        }

        /// Produced when the dimensions specified in the image header file don't match the number
        /// of pixels parsed.
        InvalidFarbfeldDimensions {
            description("Pixel count doesn't match image dimensions!")
        }
    }
}